title: Trust Wallet Developer Documentation
description: Trust Wallet Developer Documentation
remote_theme: pmarsceill/just-the-docs

permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"

plugins:
  - jekyll-seo-tag
